/**
 * ChoiceField Component
 *
 * Radio button group for single selection.
 *
 * Limepie PHP reference structure (Fields/Choice.php):
 *   <div class="btn-group btn-group-toggle{readonly}{button_class}" data-toggle="buttons">
 *     <input id="choice-{clean_key}-{token5}-{n}" class="valid-target btn-check{input_class}"
 *            type="radio" name=".." autocomplete="off" data-name=".."
 *            data-rule-name=".." value="{k}" data-is-default="{1|''}" [checked]>
 *     <label for="choice-{clean_key}-{token5}-{n}" class="btn btn-switch {element_class}{pe}">
 *       <span>{label}</span>
 *     </label>
 *     ...
 *   </div>
 *
 * Notes pinned by the reference fixtures:
 *   - every input carries data-name / data-rule-name / autocomplete="off"
 *   - NO data-default attribute; data-is-default is "1" on the default item
 *     and "" elsewhere (PHP bool interpolation)
 *   - ids end with a 5-char genRandomString token shared by the group
 *   - no role/aria attributes on the container
 */

import React, { useCallback, useMemo, useRef } from 'react';
import type { FieldComponentProps } from '../../types';
import { useI18n } from '../../context/I18nContext';
import { useFormContext } from '../../context/FormContext';
import { toBracketNotationWithPrefix } from '../../utils/dataAttributes';
import { minifyJs } from '../../hooks/legacyDisplay';
import {
  cleanStr,
  itemEntries,
  leafName,
  nextChoiceToken,
  phpString,
  ruleNameForPath,
} from './limepieParity';

/** HTML attribute-value escaping for the raw inline-JS branch. */
function escAttr(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}

/** HTML text escaping for the raw inline-JS branch. */
function escText(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/**
 * ChoiceField component
 */
export function ChoiceField({
  spec,
  value,
  onChange,
  onBlur,
  error,
  disabled,
  readonly,
  path,
}: FieldComponentProps) {
  const { t } = useI18n();
  const { keyPrefix } = useFormContext();

  // PHP: $random = genRandomString(5) — one token per choice group, stable
  // across re-renders (same pattern as FormField's uniqidRef).
  const tokenRef = useRef<string>(nextChoiceToken());

  const handleChange = useCallback(
    (optionValue: string) => {
      if (!disabled && !readonly) {
        onChange(optionValue);
      }
    },
    [onChange, disabled, readonly]
  );

  // Parse items (ordered — itemEntries keeps the spec's entry order)
  const options = useMemo(() => {
    const items = spec.items;

    if (!items || typeof items !== 'object') {
      return [];
    }

    // Check if items is dynamic
    if (!Array.isArray(items) && 'model' in items) {
      return [];
    }

    return itemEntries(items).map(([key, label]) => ({
      value: key,
      label: t(label as string | Record<string, string>),
    }));
  }, [spec.items, t]);

  // Convert path to bracket notation for name attribute
  const bracketName = toBracketNotationWithPrefix(path, keyPrefix || undefined);

  // PHP: $default = isset && !is_array ? (string)$property['default'] : null
  const defaultStr =
    spec.default !== undefined && spec.default !== null && !Array.isArray(spec.default)
      ? phpString(spec.default)
      : null;

  // The group walker substitutes the spec default into the value before the
  // field renders — the default item is checked on an empty-data render.
  const effectiveValue = (() => {
    const v = phpString(value);
    return v.length === 0 ? (defaultStr ?? '') : v;
  })();

  // PHP id prefix: 'choice-' . clean_str($key)
  const idPrefix = `choice-${cleanStr(bracketName)}`;

  // PHP: readonly (non-array) -> ' pe-none bg-secondary' on the container;
  // readonly as an array (and disableds) -> per-item ' pe-none' on labels.
  const readonlyMap = useMemo(() => {
    const map = new Set<string>();
    const ro = spec.readonly as unknown;
    if (ro && typeof ro === 'object' && !Array.isArray(ro)) {
      const items = (ro as Record<string, string[]>)[effectiveValue];
      if (Array.isArray(items)) for (const k of items) map.add(String(k));
    }
    if (Array.isArray(spec.disableds)) {
      for (const k of spec.disableds as unknown[]) map.add(String(k));
    }
    return map;
  }, [spec.readonly, spec.disableds, effectiveValue]);

  // PHP: "btn-group btn-group-toggle{$readonly}{$buttonClass}"
  const containerClass =
    'btn-group btn-group-toggle' +
    (spec.readonly === true ? ' pe-none bg-secondary' : '') +
    (spec.button_class ? ` ${spec.button_class as string}` : '');

  const dataName = leafName(path);
  const dataRuleName = ruleNameForPath(path);

  // Inline onchange/onclick JS (spec-authored, or generated by the legacy
  // display_switch transform). PHP Choice.php puts the minified JS on every
  // input; React refuses lowercase on* string props, so this branch renders
  // the legacy markup raw via dangerouslySetInnerHTML. These inputs are not
  // React-controlled — inline-JS specs are legacy jQuery forms (reference
  // parity surface), not interactive React forms.
  const inlineOnchange =
    typeof spec.onchange === 'string' && spec.onchange ? minifyJs(spec.onchange) : null;
  const inlineOnclick =
    typeof spec.onclick === 'string' && spec.onclick ? minifyJs(spec.onclick) : null;
  const initChange = Boolean((spec as Record<string, unknown>)['data-init-change']);

  if (inlineOnchange || inlineOnclick) {
    const inputClass = `valid-target btn-check${spec.input_class ? ` ${spec.input_class as string}` : ''}${error ? ' is-invalid' : ''}`;
    const html = options
      .map((option, index) => {
        const inputId = `${idPrefix}-${tokenRef.current}-${index + 1}`;
        const isDefault = (defaultStr ?? '') === option.value && defaultStr !== null;
        const isChecked = effectiveValue === option.value;
        const pe = readonlyMap.has(option.value) ? ' pe-none' : '';
        const labelClass = `btn btn-switch${spec.element_class ? ` ${spec.element_class as string}` : ''}${pe}`;
        return (
          `<input id="${escAttr(inputId)}" class="${escAttr(inputClass)}" type="radio"` +
          ` name="${escAttr(bracketName)}" autocomplete="off"` +
          ` data-name="${escAttr(dataName)}" data-rule-name="${escAttr(dataRuleName)}"` +
          ` value="${escAttr(option.value)}" data-is-default="${isDefault ? '1' : ''}"` +
          (inlineOnchange ? ` onchange="${escAttr(inlineOnchange)}"` : '') +
          (inlineOnclick ? ` onclick="${escAttr(inlineOnclick)}"` : '') +
          (initChange ? ' data-init-change="true"' : '') +
          (isChecked ? ' checked="checked"' : '') +
          `><label for="${escAttr(inputId)}" class="${escAttr(labelClass)}">` +
          `<span>${escText(option.label)}</span></label>`
        );
      })
      .join('');
    return (
      <div
        className={containerClass}
        data-toggle="buttons"
        dangerouslySetInnerHTML={{ __html: html }}
      />
    );
  }

  return (
    <div className={containerClass} data-toggle="buttons">
      {options.map((option, index) => {
        const isChecked = effectiveValue === option.value;
        const isDefault = (defaultStr ?? '') === option.value && defaultStr !== null;
        const inputId = `${idPrefix}-${tokenRef.current}-${index + 1}`;
        const pe = readonlyMap.has(option.value) ? ' pe-none' : '';

        return (
          <React.Fragment key={option.value}>
            <input
              id={inputId}
              type="radio"
              name={bracketName}
              value={option.value}
              checked={isChecked}
              onChange={() => handleChange(option.value)}
              onBlur={index === options.length - 1 ? onBlur : undefined}
              disabled={disabled}
              autoComplete="off"
              className={`valid-target btn-check${spec.input_class ? ` ${spec.input_class as string}` : ''}${error ? ' is-invalid' : ''}`}
              data-name={dataName}
              data-rule-name={dataRuleName}
              data-is-default={isDefault ? '1' : ''}
            />
            <label
              htmlFor={inputId}
              className={`btn btn-switch${spec.element_class ? ` ${spec.element_class as string}` : ''}${pe}`}
            >
              <span>{option.label}</span>
            </label>
          </React.Fragment>
        );
      })}
    </div>
  );
}

export default ChoiceField;
