import assert from 'node:assert/strict';
import test from 'node:test';

import { pipelineRecords, renderPipelineDetail, renderPipelineList } from './pipeline.mjs';

const options = { lang: 'ko', server: 'php', framework: 'react', initialization: 'ssr' };

test('canonical list is generated by CRUDUI and links each row to its detail', () => {
  const html = renderPipelineList(pipelineRecords(), options);
  assert.match(html, /class="crudui-list"/);
  assert.match(html, /href="\/detail\?id=1&amp;lang=ko&amp;server=php&amp;framework=react&amp;initialization=ssr"/);
  assert.match(html, /href="\/detail\?id=2&amp;lang=ko&amp;server=php&amp;framework=react&amp;initialization=ssr"/);
});

test('canonical list has 45 records with 20-row pages', () => {
  const records = pipelineRecords();
  assert.equal(records.length, 45);
  const page = renderPipelineList(records.slice(20, 40), { ...options, page: 2, total: records.length });
  assert.equal((page.match(/<tr>/g) ?? []).length, 21);
  assert.match(page, /data-total="45"/);
  assert.match(page, /data-page="2"/);
});

test('canonical detail is generated by CRUDUI and links the same record to its form', () => {
  const html = renderPipelineDetail(pipelineRecords()[0], options);
  assert.match(html, /class="crudui-detail"/);
  assert.match(html, /href="\/form\?id=1&amp;lang=ko&amp;server=php&amp;framework=react&amp;initialization=ssr"/);
});
